In [1]:
import numpy as np

Basics

In [11]:
a = np.array([1,2,3], dtype = 'int32')
print(len(a))

3


In [4]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(len(b))
print(b)

2
[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
#Get Dimension
a.ndim

1

In [8]:
#Get Shape
b.shape

(2, 3)

In [9]:
#Get Type
a.dtype

dtype('int64')

In [12]:
#Get Size
a.itemsize

4

In [13]:
#Get Total Size
a.nbytes
## or
## a.size * a.itemsize

12

Accessing/Changing specific elements, rows, columns, etc.

In [15]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#Get a specific element [r,c]
c[1,-2]

13

In [20]:
#Get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#Get a specific column
c[:,2]

array([ 3, 10])

In [23]:
#Getting a little more fancy [startindex:endindex:stepindex]
c[0, 1:-1:2]

array([2, 4, 6])

In [24]:
c[1,6] = 22
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 22]]


3-D example

In [27]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
#Get specific element
d[:,1,0]

array([3, 7])

In [34]:
#replace
d[:,1,:] = [[9,9],[8,8]]
print(d)
#Whatever we replace, they must be of same dimension

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Initializing Different Types of Arrays

In [36]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#All 1s matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [41]:
#Any other number
np.full((2,2), 12)

array([[12, 12],
       [12, 12]])

In [44]:
#Any other number (full_like)
np.full_like(c,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [45]:
#Random Decimal Numbers
np.random.rand(4,2)

array([[0.69987279, 0.22898666],
       [0.05471617, 0.7826972 ],
       [0.7549144 , 0.51755056],
       [0.60804165, 0.30601758]])

In [47]:
#Random Integer Values
np.random.randint(7, size = (3,3))

array([[0, 4, 1],
       [2, 3, 2],
       [0, 1, 5]])

In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
#Challenge

o = np.ones((5,5))
print(o)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

o[1:4,1:4] = z
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Mathematics

In [58]:
ab = np.array([1,2,3,4])
print(ab)

[1 2 3 4]


In [59]:
ab + 2

array([3, 4, 5, 6])

In [60]:
ab - 2

array([-1,  0,  1,  2])

In [61]:
ab * 2

array([2, 4, 6, 8])

In [62]:
ab / 2

array([0.5, 1. , 1.5, 2. ])

In [63]:
ba = np.array([1,0,1,0])
ba + ab

array([2, 2, 4, 4])

In [64]:
ab ** 2

array([ 1,  4,  9, 16])

In [67]:
np.cos(ab)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [69]:
x = np.ones((2,3))
print(x)

y = np.full((3,2),2)
print(y)

np.matmul(x,y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [70]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Statistics

In [72]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.min(stats)

1

In [74]:
np.max(stats)

6

In [75]:
np.sum(stats, axis = 0)

array([5, 7, 9])

Reorganizing Arrays

In [78]:
before = np.array([[1,2,3,8],[4,5,6,7]])
before

after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [8],
       [4],
       [5],
       [6],
       [7]])

In [79]:
#Vertically stacking vectors
v1 = np.array([1,2,3,8])
v2 = np.array([4,5,6,7])
np.vstack([v1,v2])

array([[1, 2, 3, 8],
       [4, 5, 6, 7]])

In [81]:
#Horizontally stacking vectors
v3 = np.ones((2,4))
v4 = np.zeros((2,2))
np.hstack((v3,v4))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous

Load Data from a file

In [83]:
text = np.genfromtxt('', delimiters = ',')
text

text.astype('int32')


TypeError: genfromtxt() got an unexpected keyword argument 'delimiters'

Advanced Indexing

In [84]:
filedata > 50

filedata[filedata>50]



NameError: name 'filedata' is not defined

In [86]:
##You can index with a list in numpy
de = np.array([1,2,3,4,5,6,7,8])
de[de>5]

de[[1,3,5]]

array([2, 4, 6])

In [87]:
np.any()
np.all()
(~((text > 50) & (text < 100)))

TypeError: any() missing 1 required positional argument: 'a'